import { THREE } from "../core/Renderer.js";
import { LOCATIONS } from "./Locations.js";
import { windingPath } from "./RuinsUtils.js";
import { buildDistricts } from "./DistrictGenerator.js";

export function buildScatterAndPaths(Game) {
    // 0. Ambient Debris & Scatter Walls generated by Districts
    buildDistricts(Game);

    // Connective tissue — worn paths linking each beat in narrative order
    Game.registerStructure((scene, M) => {
        const order = ["ARCHWAY", "PATH", "HOUSE", "WELL", "GARDEN", "STATUE", "TOWER", "BELL", "ROAD", "GRAVE"];
        for (let i = 0; i < order.length - 1; i++) {
            windingPath(scene, LOCATIONS[order[i]], LOCATIONS[order[i + 1]], M, { spacing: 1.3, wander: 1.8 });
        }
        windingPath(scene, LOCATIONS.HOUSE, LOCATIONS.WELL, M, { spacing: 1.2, wander: 1.2 });
        windingPath(scene, LOCATIONS.GARDEN, LOCATIONS.STATUE, M, { spacing: 1.4, wander: 1.5 });
    });
}
